Repository dForDeveloper/magic-whateverly, pull requests merged in 2019-01, with the labels that each got.

#62 Wish list prices
  package-lock.json
  package.json
  src/CardList/CardList.js
  src/CardListItem/CardListItem.js
  src/FaveList/FaveList.js
  src/FaveListItem/FaveListItem.js
  src/WishList/WishList.js
  src/WishListItem/WishListItem.js
  src/styles/_App.scss
  src/styles/_Aside.scss
  src/styles/_CardArea.scss
  src/styles/_CardList.scss
  src/styles/_CardListItem.scss
  src/styles/_Controls.scss
  src/styles/_FaveList.scss
  src/styles/_FaveListItem.scss
  src/styles/_Lists.scss
  src/styles/_WishList.scss
  src/styles/_WishListItem.scss
  src/styles/_mixins.scss
  src/styles/main.scss
Labels: enhancement

#63 Header tests
  src/CardArea/CardArea.js
  src/Header/Header.js
  src/Header/Header.test.js
  src/Header/__snapshots__/Header.test.js.snap
Labels: Testing

#67 Deck styling updates
  src/CardArea/CardArea.js
  src/Deck/Deck.js
  src/styles/_Card.scss
  src/styles/_CardArea.scss
  src/styles/_Deck.scss
  src/styles/_mixins.scss
  src/styles/_theme.scss
Labels: in progress

#68 Fix bug with new data set
  src/App/App.js
  src/CardArea/CardArea.js
Labels: in progress

#78 Add feature for providing card name suggestions as the user types
  src/App/App.js
  src/CardList/__snapshots__/CardList.test.js.snap
  src/CardListItem/__snapshots__/CardListItem.test.js.snap
  src/Controls/Controls.js
  src/Controls/Controls.test.js
  src/Controls/__snapshots__/Controls.test.js.snap
  src/Deck/Deck.js
  src/Deck/__snapshots__/Deck.test.js.snap
  src/FaveList/__snapshots__/FaveList.test.js.snap
  src/FaveListItem/__snapshots__/FaveListItem.test.js.snap
  src/Header/__snapshots__/Header.test.js.snap
  src/WishList/__snapshots__/WishList.test.js.snap
  src/WishListItem/__snapshots__/WishListItem.test.js.snap
  src/styles/_Controls.scss
Labels: in progress

#80 Aside styles
  src/Card/Card.js
  src/CardListItem/CardListItem.js
  src/Controls/Controls.js
  src/FaveListItem/FaveListItem.js
  src/WishListItem/WishListItem.js
  src/styles/_Aside.scss
  src/styles/_Card.scss
  src/styles/_CardArea.scss
  src/styles/_Controls.scss
  src/styles/_Deck.scss
  src/styles/_Lists.scss
  src/styles/_mixins.scss
Labels: in progress

#81 Change Controls component to be rendered only in My Cards
  public/magic_logo.png
  src/Aside/Aside.js
  src/Header/header-background.png
  src/styles/_Aside.scss
Labels: in progress

#82 Fix pop up so it goes away when links are clicked
  src/App/App.js
  src/CardArea/CardArea.js
  src/CardArea/CardArea.test.js
  src/CardArea/__snapshots__/CardArea.test.js.snap
Labels: in progress

#83 Readme
  README.md
Labels: in progress

#84 Update some tests
  src/Card/Card.js
  src/Controls/Controls.js
  src/Header/Header.js
  src/Header/Header.test.js
  src/WishListItem/WishListItem.test.js
Labels: in progress

#85 Publish
  package-lock.json
  package.json
Labels: in progress

#86 Revert "Publish"
  package-lock.json
  package.json
Labels: in progress
